#include "OSClass.h"
string OSClass::getOS() {
	DWORD dwOSMajorVersion       = (DWORD)malloc(sizeof(DWORD));
	DWORD dwOSMinorVersion       = (DWORD)malloc(sizeof(DWORD));
	DWORD dwSpMajorVersion       = (DWORD)malloc(sizeof(DWORD));
	DWORD dwSpMinorVersion       = (DWORD)malloc(sizeof(DWORD));
	DWORD pdwReturnedProductType = (DWORD)malloc(sizeof(DWORD));
	if (GetProductInfo(dwOSMajorVersion,dwOSMinorVersion,dwSpMajorVersion,dwSpMinorVersion, &pdwReturnedProductType)==0)
		return "-1";
	cout << "dwOSMajorVersion ->" << dwOSMajorVersion << endl;
	cout << "dwOSMinorVersion ->" << dwOSMinorVersion << endl;
	cout << "dwSpMajorVersion ->" << dwSpMajorVersion << endl;
	cout << "dwSpMinorVersion ->" << dwSpMinorVersion << endl;
	string name;
	switch (pdwReturnedProductType) {
	case  16: name = "Business N"; break;
	case  18: name = "HPC Edition"; break;
	case  64: name = "Server Hyper Core V"; break;
	case  101: name = "Windows 10 Home"; break;
	case  99: name = "Windows 10 Home China"; break;
	case  98: name = "Windows 10 Home N"; break;
	case  100: name = "Windows 10 Home Single Language"; break;
	case  80: name = "Server Datacenter (evaluation installation)"; break;
	case  145: name = "Server Datacenter, Semi-Annual Channel (core installation)"; break;
	case  146: name = "Server Standard, Semi-Annual Channel (core installation)"; break;
	case  8: name = "Server Datacenter (full installation. For Server Core installations of Windows Server 2012 and later, use the method, Determining whether Server Core is running.)"; break;
	case  12: name = "Server Datacenter (core installation, Windows Server 2008 R2 and earlier)"; break;
	case  39: name = "Server Datacenter without Hyper-V (core installation)"; break;
	case  37: name = "Server Datacenter without Hyper-V (full installation)"; break;
	case  121: name = "Windows 10 Education"; break;
	case  122: name = "Windows 10 Education N"; break;
	case  4: name = "Windows 10 Enterprise"; break;
	case  70: name = "Windows 10 Enterprise E"; break;
	case  72: name = "Windows 10 Enterprise Evaluation"; break;
	case  27: name = "Windows 10 Enterprise N"; break;
	case  84: name = "Windows 10 Enterprise N Evaluation"; break;
	case  125: name = "Windows 10 Enterprise 2015 LTSB"; break;
	case  129: name = "Windows 10 Enterprise 2015 LTSB Evaluation"; break;
	case  126: name = "Windows 10 Enterprise 2015 LTSB N"; break;
	case  130: name = "Windows 10 Enterprise 2015 LTSB N Evaluation"; break;
	case  10: name = "Server Enterprise (full installation)"; break;
	case  14: name = "Server Enterprise (core installation)"; break;
	case  41: name = "Server Enterprise without Hyper-V (core installation)"; break;
	case  15: name = "Server Enterprise for Itanium-based Systems"; break;
	case  38: name = "Server Enterprise without Hyper-V (full installation)"; break;
	case  60: name = "Windows Essential Server Solution Additional"; break;
	case  62: name = "Windows Essential Server Solution Additional SVC"; break;
	case  59: name = "Windows Essential Server Solution Management"; break;
	case  61: name = "Windows Essential Server Solution Management SVC"; break;
	case  2: name = "Home Basic"; break;
	case  67: name = "Not supported"; break;
	case  5: name = "Home Basic N"; break;
	case  3: name = "Home Premium"; break;
	case  68: name = "Not supported"; break;
	case  26: name = "Home Premium N"; break;
	case  34: name = "Windows Home Server 2011"; break;
	case  19: name = "Windows Storage Server 2008 R2 Essentials"; break;
	case  42: name = "Microsoft Hyper-V Server"; break;
	case  188: name = "Windows IoT Enterprise"; break;
	case  191: name = "Windows IoT Enterprise LTSC"; break;
	case  123: name = "Windows 10 IoT Core"; break;
	case  131: name = "Windows 10 IoT Core Commercial"; break;
	case  30: name = "Windows Essential Business Server Management Server"; break;
	case  32: name = "Windows Essential Business Server Messaging Server"; break;
	case  31: name = "Windows Essential Business Server Security Server"; break;
	case  104: name = "Windows 10 Mobile"; break;
	case  133: name = "Windows 10 Mobile Enterprise"; break;
	case  77: name = "Windows MultiPoint Server Premium (full installation)"; break;
	case  76: name = "Windows MultiPoint Server Standard (full installation)"; break;
	case  161: name = "Windows 10 Pro for Workstations"; break;
	case  162: name = "Windows 10 Pro for Workstations N"; break;
	case  48: name = "Windows 10 Pro"; break;
	case  69: name = "Not supported"; break;
	case  49: name = "Windows 10 Pro N"; break;
	case  103: name = "Professional with Media Center"; break;
	case  50: name = "Windows Small Business Server 2011 Essentials"; break;
	case  54: name = "Server For SB Solutions EM"; break;
	case  51: name = "Server For SB Solutions"; break;
	case  55: name = "Server For SB Solutions EM"; break;
	case  24: name = "Windows Server 2008 for Windows Essential Server Solutions"; break;
	case  35: name = "Windows Server 2008 without Hyper-V for Windows Essential Server Solutions"; break;
	case  33: name = "Server Foundation"; break;
	case  9: name = "Windows Small Business Server"; break;
	case  25: name = "Small Business Server Premium"; break;
	case  63: name = "Small Business Server Premium (core installation)"; break;
	case  56: name = "Windows MultiPoint Server"; break;
	case  79: name = "Server Standard (evaluation installation)"; break;
	case  7: name = "Server Standard (full installation. For Server Core installations of Windows Server 2012 and later, use the method, Determining whether Server Core is running.)"; break;
	case  13: name = "Server Standard (core installation, Windows Server 2008 R2 and earlier)"; break;
	case  40: name = "Server Standard without Hyper-V (core installation)"; break;
	case  36: name = "Server Standard without Hyper-V"; break;
	case  52: name = "Server Solutions Premium"; break;
	case  53: name = "Server Solutions Premium (core installation)"; break;
	case  11: name = "Starter"; break;
	case  66: name = "Not supported"; break;
	case  47: name = "Starter N"; break;
	case  23: name = "Storage Server Enterprise"; break;
	case  46: name = "Storage Server Enterprise (core installation)"; break;
	case  20: name = "Storage Server Express"; break;
	case  43: name = "Storage Server Express (core installation)"; break;
	case  96: name = "Storage Server Standard (evaluation installation)"; break;
	case  21: name = "Storage Server Standard"; break;
	case  44: name = "Storage Server Standard (core installation)"; break;
	case  95: name = "Storage Server Workgroup (evaluation installation)"; break;
	case  22: name = "Storage Server Workgroup"; break;
	case  45: name = "Storage Server Workgroup (core installation)"; break;
	case  1: name = "Ultimate"; break;
	case  71: name = "Not supported"; break;
	case  28: name = "Ultimate N"; break;
	case  0: name = "An unknown product"; break;
	case  17: name = "Web Server (full installation)"; break;
	case  29: name = "Web Server (core installation)"; break;
	}


	return name;
}